### ISSUE TITLE
problem on new google apis update

### ISSUE THREAD

**Issue by halukmy** [pocheshire/BottomNavigationBar#33] opened 2016-11-02 11:46 UTC
can you check it?

**Comment by bchaitani** [comment] 2016-11-15 10:29
Any solution for this issue?

**Comment by jpozo20** [comment] 2016-11-18 07:08
#35 
I think I know what the problem is. I'll be working on a fork while the author answers the issues.

**Comment by jpozo20** [comment] 2016-11-21 21:55
Please, try this package and tell meif it works.

[jpozo.BottomNavigationBar-Nougat.1.4.0.2.zip](https://github.com/pocheshire/BottomNavigationBar/files/604875/jpozo.BottomNavigationBar-Nougat.1.4.0.2.zip)

**Comment by modplug** [comment] 2016-11-22 19:29
@jpozo20  Please make a this a PR

**Comment by jpozo20** [comment] 2016-11-23 01:21
@modplug I think the autor downgrades the libraries version so Xamarin.Forms could be supported. What I did was updated to the latests libraries and I think that would be a breaking change.

**Comment by pocheshire** [comment] 2016-11-23 06:52
fixed in 1.4.0.3 version

**Closed by pocheshire** 2016-11-23 06:52 UTC
